### ISSUE TITLE
问题真机运行报错,

### ISSUE THREAD

**Issue by adminqiuchi** [coolnameismy/BabyBluetooth#1]
出现了Could not build module 'CoreBluetooth',我是IOS初学者,有罪莫怪

**Comment by coolnameismy** [comment]
BabyBluetooch是一个蓝牙操作库，请导入BabyBluetooch代码。你可以更新下最新的代码：https://github.com/coolnameismy/BabyBluetooth <https://github.com/coolnameismy/BabyBluetooth>

请问你是在哪里下的程序不能编译？
