### ISSUE TITLE
请增加cancelAllPeripheralsConnection的AtChannel方式

### ISSUE THREAD

**Issue by ufiejfs** [coolnameismy/BabyBluetooth#110]
代理有
setBlockOnCancelAllPeripheralsConnectionBlock
setBlockOnCancelAllPeripheralsConnectionBlockAtChannel
但执行方法只有
cancelAllPeripheralsConnection
请增加其AtChannel方式

**Comment by OliverLee1987** [comment]
都两个月了, 还没有回复😂
