### ISSUE TITLE
连接蓝牙外设成功，回调方法不回调连接成功

### ISSUE THREAD

**Issue by huangmoxianganquan** [coolnameismy/BabyBluetooth#116]
你好，我这边连接一个蓝牙外设实际上已经连接成功了，但是在 [self.baby setBlockOnConnectedAtChannel:kPeripheralChannel block:^(CBCentralManager *central, CBPeripheral *peripheral) 这个方法中并没有回调，蓝牙状态一直显示正在连接，这是怎么回事呢

**Comment by coolnameismy** [comment]
请检查你的channel是否混乱，简单业务不需要用channel去做区分
