### ISSUE TITLE
一个关于注释的小建议

### ISSUE THREAD

**Issue by clayzhu** [coolnameismy/BabyBluetooth#12]
您好，BabyBluetooth 非常好用，对蓝牙开发帮助很大，开发效率高了很多。有一个小建议，目前您的代码中使用 // 来注释，这样对编程时查看该方法不太方便，可否在以后的更新中改用 /***/ 进行注释，应该对大家使用时查看注释会更方便。谢谢。

**Comment by coolnameismy** [comment]
好的，谢谢提醒。我会把最外层方法名的注释改为/***/
