### ISSUE TITLE
蓝牙和手机配对后可以正常使用,但是总是几分钟断开一次,然后重连上又可以正常使用 errorCode = 6

### ISSUE THREAD

**Issue by afeature** [coolnameismy/BabyBluetooth#125]
didDisconnectPeripheral for XXX with error: The connection has timed out unexpectedly. errorCode = 6

**Comment by coolnameismy** [comment]
连接不稳定一般和设备蓝牙通讯模块的质量关系最大，和环境也有一定的关系，但这个都属于正常情况
