### ISSUE TITLE
项目想用这个库，该库不会对app上架造成影响吧，求确认？

### ISSUE THREAD

**Issue by devkou** [coolnameismy/BabyBluetooth#129]
看到有一个issuse说 用到私有api 上架悲剧，去掉就好了，但是查看源码也没看到啊，希望作者大大能给一个确信，项目中需要用到蓝牙，感觉这个库很好用，已经集成进自己demo中测试完毕了
问题：有没有使用私有api，对上架是否有影响？

**Comment by coolnameismy** [comment]
没有用私有api哦，感谢你的支持🙏
