### ISSUE TITLE
Reading is not permitted

### ISSUE THREAD

**Issue by vicky1221** [coolnameismy/BabyBluetooth#14]
我在调取babyBluetooth.channel(channelOnCharacteristicView).characteristicDetails(self.currPeripheral,self.characteristic)的时候一直报Reading is not permitted 我是蓝牙小白， 能告诉我为什么吗

**Comment by coolnameismy** [comment]
每个characteristic都有权限，你读取的这个characteristic没有read的权限所有会报错。

**Comment by NiYien** [comment]
> 每个characteristic都有权限，你读取的这个characteristic没有read的权限所有会报错。
你好，我看代码，是将read和notify放在一起的，ios13后，notify使用read会提示权限错误，请问这个要怎么修改啊

**Comment by zhongdaima** [comment]
> > 每个characteristic都有权限，你读取的这个characteristic没有read的权限所有会报错。
> > 你好，我看代码，是将read和notify放在一起的，ios13后，notify使用read会提示权限错误，请问这个要怎么修改啊

请问老哥这个问题解决了么，我现在订阅通知notify之后，一直报错：Reading is not permitted
