### ISSUE TITLE
iOS11下有些情况下会出现无法发现服务的问题

### ISSUE THREAD

**Issue by change2hao** [coolnameismy/BabyBluetooth#146]
升级到iOS11，有些手机会遇到 `- (void)peripheral:(CBPeripheral *)peripheral didDiscoverServices:(NSError *)error` 不回调的问题，请问谁遇到过？

**Comment by jimmylot** [comment]
我遇到过，但是我是在设备异常断开之后，就发现不了服务了

**Comment by change2hao** [comment]
@leisong1125 我只在iOS11下发现了这个问题，目前只有reset网络设置或者关机重启才能解决，不知道你有没有更好的办法，我确定外设的服务是没问题的，只是系统一直发现不了

**Comment by jimmylot** [comment]
我正要回你，我是在升级硬件过程中，强制断电会导致发现不了服务，之后所有同型号的设备都出现这个问题，我尝试了一下重启手机可以解决，目前还在不断测试中

**Comment by change2hao** [comment]
已经解决

**Comment by jimmylot** [comment]
怎么 解决的 什么问题造成的

**Comment by change2hao** [comment]
@leisong1125 外设的蓝牙固件问题，设置的最小间隔和最大间隔不符合Apple标准，跟App没有关系

**Comment by jimmylot** [comment]
谢谢 您的回答 我们这边 要测试 一线 才能知道 是不是一样的问题

**Comment by XanderXu** [comment]
@change2hao 请问这个最小间隔,最大间隔的标准是多少? 苹果有没有文档啊?我也遇到这个问题了

**Comment by change2hao** [comment]
https://developer.apple.com/library/content/qa/qa1931/_index.html 希望对你有帮助 @XanderXu

**Comment by XanderXu** [comment]
@change2hao 感谢了,我的不是这个问题.但是从你的链接中找到了其他有用信息,是外设的蓝牙特征地址在重启后会变动,但又没有实现serviceChange方法导致的,iOS系统级缓存出现问题.
如果外设的服务和特征地址会变动,按蓝牙规范需要在serviceChange中通知外部刷新...
这个问题花了我两个月才解决...
