### ISSUE TITLE
关于设置过滤条件

### ISSUE THREAD

**Issue by JJCoderiOS** [coolnameismy/BabyBluetooth#16]
您好,目前我们公司的项目正在使用这个框架.确实方便很多,很好用.我的问题如下:希望得到回复,谢谢!

在设置过滤条件的时候,我搜索指定 设备的信号,然后将搜索到的信号记录下来,但是当设备的信号消失的时候现在就不会返回true了,我也就没有办法记录了,具体截图上传了,我想要在 这个设备没有信号的时候也记录他.应该怎么处理呢?

**Comment by coolnameismy** [comment]
截图在哪呢？

**Comment by JJCoderiOS** [comment]
![Uploading h.png…]()

**Comment by JJCoderiOS** [comment]
![h](https://cloud.githubusercontent.com/assets/8589860/12188915/830ccc4e-b5f4-11e5-8aca-74384ea305a3.png)

**Comment by JJCoderiOS** [comment]
因为有很多设备,我设置过滤条件是只搜索我指定的这个,但是 当我这个设备没有信号后,就return NO了

**Comment by coolnameismy** [comment]
没问题啊，你这样写是对的。 你这个设备没型号后，进入filter的设备就都不是你关心的设备，自然会return no
