### ISSUE TITLE
重新扫描问题

### ISSUE THREAD

**Issue by Yangxiiii** [coolnameismy/BabyBluetooth#162]
您好,我最近在写项目中使用该框架遇到一个问题,我在连上某个蓝牙设备后将该设备设为自动重连.[_baby AutoReconnect:_currentPeripheral];    然后在设备断开5秒后将它从自动重连中去除 [_baby AutoReconnectCancel:_currentPeripheral]; 并重新开启扫描,这时候我发现一旦这个蓝牙设备可以被连接会直接跳过条件过滤重新连接,并且不会去搜索蓝牙服务和特征. @coolnameismy   能帮我看一下是什么原因吗?  我的本意是想要在app连上某个设备后记住该设备,在该设备断开重连5秒没连上才去重新扫描连接别的设备.

**Comment by SYJshang** [comment]
你好，你解决这个问题了么，我也遇到这个问题，解决了麻烦告诉一下解决方法。

**Comment by Yangxiiii** [comment]
解决了, 没用系统的自动重连而是把需要自动重连的设备自己保存一下. 在断开的时候重新开始扫描过滤判断设备.

**Comment by SYJshang** [comment]
谢谢回复，能加下qq么，我还有点问题想要请教您一下。我的qq 1334858022.

**Comment by Yangxiiii** [comment]
要验证加不了, 你加我吧. 137594351
