### ISSUE TITLE
连接的地方可以再优化

### ISSUE THREAD

**Issue by sandywux** [coolnameismy/BabyBluetooth#17]
反复研究了代码，整体思路用链式函数去处理感觉很新颖。
但是关于蓝牙连接，不知作者有没有注意到这两个API:
- (NSArray<CBPeripheral *> *)retrievePeripheralsWithIdentifiers:(NSArray<NSUUID *> *)identifiers 
- (NSArray<CBPeripheral *> *)retrieveConnectedPeripheralsWithServices:(NSArray<CBUUID *> *)serviceUUIDs 
第一个只要是当前手机曾经连接过的CBPeripheral 可以通过UUID属性直接获取对象。
第二个只要是当前手机连接着的CBPeripheral对象，可以通过Service UUID来直接获取对象，注意就算不是当前的APP连接的也是可以获取到，如果不用这个API，有可能设备被当前手机连着，去扫描会扫描不到。
因为没有扫描步骤，这两个API可以大大减少连接设备的时间，同时也可以节约手机的能耗（虽然这点能耗没有卵用）
建议实现这两个方法，第二个比较简单，第一个需要用到本地存储，略复杂。

**Comment by coolnameismy** [comment]
你的建议非常好，感谢，我会列入下个版本计划。
