### ISSUE TITLE
断开单个Peripheral问题

### ISSUE THREAD

**Issue by Cregin** [coolnameismy/BabyBluetooth#190]
执行
`[baby cancelPeripheralConnection:peripheral];`
断开单个Peripheral怎么也执行下面这个回调，如何区分断开的是全部还是单个？

```
[baby setBlockOnCancelAllPeripheralsConnectionBlock:^(CBCentralManager *centralManager) {
        NSLog(@"===断开所有已连接Peripheral");
    }];
```

**Comment by yinanwang1** [comment]
`//判断是否全部链接都已经段开,调用blockOnCancelAllPeripheralsConnection委托
    if ([self findConnectedPeripherals].count == 0) {
        //停止扫描callback
        if ([currChannel blockOnCancelAllPeripheralsConnection]) {
            [currChannel blockOnCancelAllPeripheralsConnection](centralManager);
        }
        //    BabyLog(@">>> stopConnectAllPerihperals");
    }`
查看源码，你断开单个Peripheral导致回调了`setBlockOnCancelAllPeripheralsConnectionBlock:`是因为你当前断开这个Peripheral后没有了其他的连接，所以才调用了。
