### ISSUE TITLE
如何可以app（center模式）在手机后台运行的时候自动连接外设的蓝牙设备呢

### ISSUE THREAD

**Issue by beiliubei** [coolnameismy/BabyBluetooth#20]
![image](https://cloud.githubusercontent.com/assets/1127875/12719894/d1711128-c932-11e5-9594-a7b947488e99.png)

这么写没有回调

**Comment by coolnameismy** [comment]
回调就是使用baby的实例，调用setBlockXXXX方法就可以了设置了。

**Comment by beiliubei** [comment]
但是进入后台运行的时候，不执行block里面的回调，前台没问题

**Comment by coolnameismy** [comment]
后台模式需要声明，可以参考这个地址
https://github.com/coolnameismy/BabyBluetooth/wiki/%E5%90%8E%E5%8F%B0%E6%A8%A1%E5%BC%8F

**Comment by beiliubei** [comment]
![image](https://cloud.githubusercontent.com/assets/1127875/12753221/212ab808-ca01-11e5-80a9-93ee40039437.png)

已经加了

**Comment by coolnameismy** [comment]
那肯定会执行的。你可以先做个测试，看看后台模式是否可以正常使用。
