### ISSUE TITLE
一台手机做中心 一台手机做外设服务器，为什么没有反应？？？

### ISSUE THREAD

**Issue by ITMeow** [coolnameismy/BabyBluetooth#24]
如题，我使用手机和mac的配对就可以

**Comment by coolnameismy** [comment]
手机需要发送广播，mac也是需要发送广播的。可以看demo中有使用手机模拟ble外设的代码，启动起来然后就可以发送广播。如果你是这么做的，那么之前有个朋友也和你遇到一样的问题，他是因为手机做外设的时候没有给外设添加名称，所以给中心忽略了。后面我会在babybluetooth外设模式下增加一个外设默认名称。

**Comment by ITMeow** [comment]
@coolnameismy 那目前的外设添加名称是在代码里填写还是在xcode的设置中设置的？？？
