### ISSUE TITLE
请更新 pod 版本号

### ISSUE THREAD

**Issue by Sean-Wang** [coolnameismy/BabyBluetooth#25]
在 Commit 24074f9d0fce7e4033c1393668f29f892ab53b24 后，请更新 pod 版本号，以便通过 pod update 进行升级。谢谢。

**Comment by coolnameismy** [comment]
别着急~ 现在积累的都是小改动，最近还会有一些小改动会一起更新pod到下一个版本

**Comment by Sean-Wang** [comment]
赞。

**Comment by Sean-Wang** [comment]
还不考虑更新一个小版本的 pod 号吗？

**Comment by coolnameismy** [comment]
还在准备几个新功能，近期会更新一个版本
