### ISSUE TITLE
获取到描述的值方法拼写小问题

### ISSUE THREAD

**Issue by qyzhaojinxi** [coolnameismy/BabyBluetooth#33]
//设置读取到Characteristics描述的值的block
- (void)setBlockOnReadValueForDescriptors:(void (^)(CBPeripheral *peripheral,CBDescriptor *descriptorNSError,NSError *error))block {
    [[babySpeaker callback]setBlockOnReadValueForDescriptors:block];
}

descriptorNSError去掉NSError
顺便改一下说明里的”even bady can use “吧

**Comment by coolnameismy** [comment]
感谢你的细心，确实是我在复制粘贴的时候，命名有问题，正在修复。

**Comment by qyzhaojinxi** [comment]
😊我才要感谢你写了这个类库呢
