### ISSUE TITLE
findConnectedPeripheral这个方法不能获取已经连接的Peripheral

### ISSUE THREAD

**Issue by yuanzj** [coolnameismy/BabyBluetooth#35]
非常感谢coolnameismy分享的蓝牙库，我在使用的时候发现findConnectedPeripheral这个方法不能获取已经连接的Peripheral。
**== 比较的是指针地址吧**
```
- (CBPeripheral *)findConnectedPeripheral:(NSString *)peripheralName {
    for (CBPeripheral *p in connectedPeripherals) {
        if (p.name == peripheralName) {
            return p;
        }
    }
    return nil;
}
```
另外后续是否会有api可以指定queue 让数据接收在异步线程运行的，顺便吐槽一下用BLE做大文件的固件升级太坑了。
`
 [[CBCentralManager alloc]initWithDelegate:self queue:nil];
`

**Comment by coolnameismy** [comment]
感谢指出问题。

````
另外后续是否会有api可以指定queue 让数据接收在异步线程运行的
````

这个api可以加，后续版本会提供，但是估计用的人会比较少吧，CBCentralManager是单例，指定线程后是否还可以再次通过重新实例化CBCentralManager修改线程，还需要研究一下。
