### ISSUE TITLE
Baby.scanForPeripherals().connectToPeripherals().begin();为什么连接没有验证码输入那个弹窗

### ISSUE THREAD

**Issue by jasamin** [coolnameismy/BabyBluetooth#36]
用原生的写会有提示验证 ，但是用baby这个来连接就没有验证，然后就获取不到服务那些，怎么回事呢

**Comment by coolnameismy** [comment]
验证？你说的是设备配对吧，只会发生在设备首次配对成功后，就不会再出现了，好什么库没关系，和你后面的疑问也没关系

发自我的 iPhone

**Comment by xiaobeifeng** [comment]
用原生写连接外设就不会出现弹框。用BabyBlueTooth就会出现配对弹框，也是这个原因吗？？

**Comment by xiaobeifeng** [comment]
用原生写连接外设就不会出现弹框。用BabyBlueTooth就会出现配对弹框，这个是什么原因呢？？
