### ISSUE TITLE
小白请教,关于发送数据.

### ISSUE THREAD

**Issue by yy182038** [coolnameismy/BabyBluetooth#38]
这里有一块OBD模拟器电路板,需要发送数据才能返回数据,我用您的框架可以通过蓝牙连接,写入数据也返回成功,但是模拟器返回的数据,我没有找到,安卓是可以直接返回数据的.请说明一下,谢谢.

**Comment by coolnameismy** [comment]
返回是通过notiy和read得到的


发自我的 iPhone

**Comment by yy182038** [comment]
我用您的demo把"Byte b = 0X01"改成了"Byte b = 01 0D"(这个用来获得车速)把有write权限的都写了,把有notify权限的也都点开了,还是没看到返回值.

**Comment by coolnameismy** [comment]
写操作是没有返回值的，但是有一个写成功后的委托。返回值可以通过notiy或read其它特征值获取
