### ISSUE TITLE
findConnectedPeripherals返回的 peripherals是 disconnected的

### ISSUE THREAD

**Issue by beiliubei** [coolnameismy/BabyBluetooth#39]
![image](https://cloud.githubusercontent.com/assets/1127875/14566031/61249224-0360-11e6-8dd7-e31392ef31ca.png)

**Comment by beiliubei** [comment]
且对这个 peripheral进行 AutoReconnect 没有成功

**Comment by coolnameismy** [comment]
AutoReconnect 直接设置使用，不需要断线后使用。这个方法有测试用例覆盖的，不会有问题。你说的findConnectedPeripherals是disconnect，那个我会再查一下看看
