### ISSUE TITLE
如何通过App 连接蓝牙Ble 和 A2DP 协议 ？

### ISSUE THREAD

**Issue by arrfu** [coolnameismy/BabyBluetooth#41]
用App  连接蓝牙设备后，手机播放歌曲声音仍然从手机出来，除非手动到设置里面将另一个协议A2DP 连接上后，推送的歌曲才能从蓝牙设备出来。请问有什么便捷的解决方案吗？

**Comment by coolnameismy** [comment]
对这方面不是很了解，这个issue放一个月看看有没有了解的人会给你回答，祝好运。

**Comment by dawangjiaowolaixunshan** [comment]
这个方面没经验 .. 坐等大神回答 ..
