### ISSUE TITLE
切换 channel 后   !!!设备当前处于非连接状态

### ISSUE THREAD

**Issue by sadenner** [coolnameismy/BabyBluetooth#43]
控制台输出  >>>已切换到eg    !!!设备当前处于非连接状态   为什么会断开呢？

**Comment by coolnameismy** [comment]
一种可能是你掉了断开设备的方法主动断开了设备，比如baby的stop方法，另一种可能是设备不稳定就会断线，这种情况很常见。

**Comment by sadenner** [comment]
谢谢。。设备刚才卡死了
