### ISSUE TITLE
请问swift版本什么时候发布呀？

### ISSUE THREAD

**Issue by mcyaiahua** [coolnameismy/BabyBluetooth#45]
如题

**Comment by coolnameismy** [comment]
可以关注 [BabyBluetooth-swift](https://github.com/coolnameismy/BabyBluetooth-swift
) 项目，目前应为时间关系，没有完全用swift实现，但是做了兼容swift的处理, 使用说明点击：[https://github.com/coolnameismy/BabyBluetooth-swift](https://github.com/coolnameismy/BabyBluetooth-swift)
