### ISSUE TITLE
有关蓝牙打印 打印机无响应的问题

### ISSUE THREAD

**Issue by TzyTman** [coolnameismy/BabyBluetooth#54]
公司现在买的热敏打印机都是支持esc/pos命令的 指示打印速度不一样 其它的都是一样的  但是一台可以打 一台不行   我昨天晚上弄了好久都不知道问题的所在 您说的找硬件工程师做设备联调。但是我昨天下了几个第三方的蓝牙打印SDK两台都可以打印？

**Comment by TzyTman** [comment]
公司现在买的热敏打印机都是支持esc/pos命令的 指示打印速度不一样 其它的都是一样的  但是一台可以打 一台不行   我昨天晚上弄了好久都不知道问题的所在 您说的找硬件工程师做设备联调。但是我昨天下了几个第三方的蓝牙打印SDK两台都可以打印？

**Comment by coolnameismy** [comment]
不知道你的问题，所有的sdk蓝牙调用的方法底层方法都是一样的，不应该存在你说的那种问题。
