### ISSUE TITLE
关于功耗问题！

### ISSUE THREAD

**Issue by swiftoc-dev** [coolnameismy/BabyBluetooth#55]
在使用过程中，发现以下两个问题，暂时没有找到解决方法：
1、连接10分钟左右，会断开连接，然后自动重连，频率相当高。
2、功耗非常大，每隔30ms左右进行一次通信，造成功耗过大。
以下图片是安卓和iOS测试对比：
![69c350d3ee44648a870c86cf274d3a02](https://cloud.githubusercontent.com/assets/11433677/15853437/9c40a1d6-2cd7-11e6-8b3a-e04342771338.jpg)
![f6043a71fd1fc860ed96e7663ce9de0a](https://cloud.githubusercontent.com/assets/11433677/15853435/9b948a04-2cd7-11e6-8850-0698dfc174ab.jpg)
@coolnameismy 谢谢

**Comment by coolnameismy** [comment]
断线的时间是固定的吗？你的现象挺奇怪的，蓝牙协议里面有不少比较底层的协议上的规定，但是作为app应用层，没有能仔细研究过。

断线你用的是connect方法没有开代码吧？
android直连用的是mac地址，ios用的是identify，是不是可能是这个原因？

发自我的 iPhone

**Comment by swiftoc-dev** [comment]
1.断线的时间不是固定的，时间都在10分钟左右，有时早一些，有时迟一些。不稳定是可以确定的。安卓手机连接，没有出现这种情况。
2.连接成功后，APP只做了读取硬件设备上传的数据，并没有进行其他操作。
3.安卓连接方式我并不清楚，iOS连接是指定服务UUID的，如下图：
![11](https://cloud.githubusercontent.com/assets/11433677/15854211/323e2430-2cdb-11e6-8f44-9cb8759f5a2c.png)
![22](https://cloud.githubusercontent.com/assets/11433677/15854253/7f7b93d6-2cdb-11e6-8379-b6a37ddfb878.png)


@coolnameismy 谢谢。

**Comment by coolnameismy** [comment]
10分钟掉线一次我觉得是正常的可以接受的，掉线后发一次重连请求

发自我的 iPhone

**Comment by coolnameismy** [comment]
我猜的一些可能的原因，你android端和ios端和设备的通信方式不同。比如订阅一个用的indicate,一个notify，写数据一个用的onresponse，一个用的withoutresponse，如果读写数据都很频繁，是有可能产生你说的这些问题的。

**Comment by ruhuaby** [comment]
我觉得可能是你的硬件在处理某个任务时时间用的过长，导致蓝牙连接断开的。

**Comment by coolnameismy** [comment]
一般和硬件关系会比较大一些
