### ISSUE TITLE
能否在连接上一个蓝牙的情况下，保持扫描其它蓝牙

### ISSUE THREAD

**Issue by mydy1987** [coolnameismy/BabyBluetooth#59]
Demo里，要进行扫描，是先调用了以下的：[baby cancelAllPeripheralsConnection]; 
-(void)viewDidAppear:(BOOL)animated{
    NSLog(@"viewDidAppear");
    //停止之前的连接
    [baby cancelAllPeripheralsConnection];
    //设置委托后直接可以使用，无需等待CBCentralManagerStatePoweredOn状态。
    baby.scanForPeripherals().begin();
    //baby.scanForPeripherals().begin().stop(10);
}

我试了一下，当把Demo里的[baby cancelAllPeripheralsConnection]注释掉后，点击界面中的一个蓝牙，进入后，再返回这个界面，Baby不会继续扫描。

一般的app都有这个需求，查看当前周围蓝牙设备列表，连接上的就打勾，没有连上的保持扫描和显示。我试了多种方法还是没有达到这个效果，请教楼主一下，这个功能如何实现呢。😉

**Comment by coolnameismy** [comment]
可以的
