### ISSUE TITLE
iOS 是不是不能得到已经连接的设备

### ISSUE THREAD

**Issue by JiesonWu** [coolnameismy/BabyBluetooth#6]
- (void)centralManager:(CBCentralManager *)central didRetrieveConnectedPeripherals:(NSArray *)periphe

发现你没有实现这个类

**Comment by coolnameismy** [comment]
这个没有实现。最新的代码更新提供了一个方法获取到centralManager对象，有了它，你就可以调用原生的方法。详细内容请看wiki，更新说明
https://github.com/coolnameismy/BabyBluetooth/wiki/%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E

**Comment by coolnameismy** [comment]
````objc
//获取当前连接的peripherals
-(NSArray *)findConnectedPeripherals;
//获取当前连接的peripheral
-(CBPeripheral *)findConnectedPeripheral:(NSString *)peripheralName;
//获取当前corebluetooth的centralManager对象
-(CBCentralManager *)centralManager;
````
