### ISSUE TITLE
关于切换委托频道,   baby.channel(channelName)后面必须跟scan或者connect方法才能切换成功?

### ISSUE THREAD

**Issue by ldhios** [coolnameismy/BabyBluetooth#61]
我试了.如果直接baby.channel(channelName).begin();是会报错的.要先扫描或者connect之类的
//切换到委托频道
    baby.channel(channelName)
    //扫描设备并chan开始执行
    .scanForPeripherals().begin();

**Comment by ldhios** [comment]
我的意思是: 如果有一个设备列表, 我一进入设备列表的时候就已经把当前页面上的设备全部connect上了. 点击对应cell上的设备,进入设备详情页. 但是我进入设备详情页控制器的的时候, 如果我要切换channel. 还是必须先执行scan. connect 才能切换委托.

**Comment by ldhios** [comment]
因为我觉得当前设备已经是连接上了的 没必要再去连接扫描.

**Comment by coolnameismy** [comment]
可以不扫描的。have方法可以传对象

发自我的 iPhone

在 2016年12月6日，上午11:13，Lance <notifications@github.com<mailto:notifications@github.com>> 写道：


因为我觉得当前设备已经是连接上了的 没必要再去连接扫描.

―

**Comment by ldhios** [comment]
我是用have方法持有已经连接的设备的. 然后还是需要再次调用connect方法才能切换channel. 这样的话就是再次连接了吗?

**Comment by coolnameismy** [comment]
可以看demo的示例

**Comment by ldhios** [comment]
您的demo 没有这种示例
