### ISSUE TITLE
手机作为蓝牙周边设备，只对外提供了startAdvertising(开启广播)的方法，没有提供stopAdvertising(停止广播)的方法

### ISSUE THREAD

**Issue by sontie** [coolnameismy/BabyBluetooth#69]
手机作为蓝牙周边设备，只对外提供了startAdvertising(开启广播)的方法，没有提供stopAdvertising(停止广播)的方法，比如要修改广播内容的话，直接重复发送新内容广播的话，内容并不会修改，需要先停止广播才可以修改广播内容。

**Comment by coolnameismy** [comment]
好的，这个是合理的需求，会仔下个版本更新

发自我的 iPhone
