### ISSUE TITLE
发现一个bug，由于硬件需求，改了蓝牙的名字，但是通过Baby搜索出来的结果和底层不一样

### ISSUE THREAD

**Issue by Pijiayou** [coolnameismy/BabyBluetooth#70]
![09 02](https://cloud.githubusercontent.com/assets/16968630/18191021/a2b36574-70f9-11e6-8795-5c9f93b67f4d.png)
现在我还没找到原因

**Comment by coolnameismy** [comment]
peripheral.name 和 KCAdvDataLocalname是两回事
