### ISSUE TITLE
关于手机设备 一对多 的问题

### ISSUE THREAD

**Issue by ThatCyan** [coolnameismy/BabyBluetooth#72]
您好使用了你的蓝牙库，可以实现连接一个设备并控制。想问一下您 ，如果我需要同时控制这些设备，思路应该是怎么样的？

**Comment by coolnameismy** [comment]
通过委托拿到的peripheral.name或者uuid区分不同设备，进行处理。

**Comment by ThatCyan** [comment]
打扰了，想问下为什么我调用

_baby.having(self.currPeripheral).and.channel(channelOnPeropheralView).then.connectToPeripherals().discoverServices().discoverCharacteristics().readValueForCharacteristic().discoverDescriptorsForCharacteristic().readValueForDescriptors().begin();

这个方法

会把我当前搜索的所有相同类型 不同peripheral设备 都连接上。。。

在 2016-09-13 18:52:22，"刘彦玮" <notifications@github.com> 写道：


通过委托拿到的peripheral.name或者uuid区分不同设备，进行处理。

**Comment by coolnameismy** [comment]
这个方法不应该放在委托中被调用。

**Comment by xiaomianbao** [comment]
那我想实现在连接蓝牙的情况下  下次连接不用从设备列表中选择设备  那就必须在扫描到外设的委托中调用连接外设的一系列方法    不能放委托 那要实现这种效果该怎么做/???? 每次都要去设备列表选择设备???
