### ISSUE TITLE
关于Baby使用问题

### ISSUE THREAD

**Issue by Pijiayou** [coolnameismy/BabyBluetooth#73]
![2016 09 14 baby](https://cloud.githubusercontent.com/assets/16968630/18499237/8bddcdce-7a6f-11e6-903c-f1ca55818903.png)
博主，中间这个方法怎么理解？读取Characteristics的值中间为什么需要查找字段订阅？请问作用是什么？

**Comment by coolnameismy** [comment]
找到对应的charateristic，派发相关蓝牙事件
