### ISSUE TITLE
在iOS10中调用retrieveConnectedPeripheralsWithServices:无效

### ISSUE THREAD

**Issue by wanghe826** [coolnameismy/BabyBluetooth#75]
在iOS10中调用retrieveConnectedPeripheralsWithServices:方法返回0个（蓝牙设备已经跟系统连接配对了），但是在iOS9当中却是正常的，这是为什么呢？

**Comment by fshmjl** [comment]
对呀，这是什么情况？

**Comment by wanghe826** [comment]
@fshmjl   盆友， 你也碰到了这个问题吗？  真的是蛮奇怪的

**Comment by fshmjl** [comment]
是呀，现在已经解决了

**Comment by wanghe826** [comment]
请问一下 你是怎么结局的呢？  能否分享一下方法？  谢谢！！

**Comment by fshmjl** [comment]
这个分为两个端，一个是中心设备，一个是外围设备，所以要在两台机子上运行不同的程序，中心设备运行BabyBluetoothAppDemo，外围设备运行这个BluetoothStubOnIOS

**Comment by fshmjl** [comment]
我这样理解我都不知道对不对，但是这样的确能行

**Comment by fshmjl** [comment]
我这样理解我都不知道对不对，但是这样的确能行

**Comment by wanghe826** [comment]
但是我的外围设备不是iDevice啊，我的中心设备才是iphone

**Comment by wanghe826** [comment]
能否加个qq交流下，491506084

**Comment by fshmjl** [comment]
1032872992这个人，你加了问下，我这边只是感兴趣在学习这个，但是我没有硬件外设，这个人刚接通与硬件的通信

**Comment by fshmjl** [comment]
我加你了

**Comment by wanghe826** [comment]
好的，谢谢🙏
