### ISSUE TITLE
蓝牙断开后, 重新连接设备, 会无视过滤条件同时连接别的设备, 而且数据也不能接收到了

### ISSUE THREAD

**Issue by xiaomianbao** [coolnameismy/BabyBluetooth#78]
这是我的做法:
1.第一次进来扫描设备会有设备列表  
2.保存选择外设的 peripheral.identifier.UUIDString 
3.断开蓝牙,再次进入连接页面,判断保存的标志位 和 扫描到的外设的标志位 ,一致的话连接外设
4.最后发现再次连接会随便乱连别的设备,目标设备的notify也不会发送了 

[_baby setBlockOnDiscoverToPeripherals:^(CBCentralManager *central, CBPeripheral *peripheral, NSDictionary *advertisementData, NSNumber *RSSI) {
        NSLog(@"搜索到了设备:%@  广播识别id =%@",peripheral.name,peripheral.identifier);

```
    if ([peripheral.name isEqualToString:@"OCULAR"] &&peripheral.name.length) {

        NSString *blueToothIdentify = UNGetObject(BlueTootchPeripheral);
        if ([blueToothIdentify isEqualToString:peripheral.identifier.UUIDString] ) {
            NSLog(@"已经连接过,直接连接  设备-->%@",peripheral.name);
            weakSelf.peripheral_my = peripheral;
            weakSelf.baby.having(peripheral).connectToPeripherals().discoverServices().discoverCharacteristics().readValueForCharacteristic().discoverDescriptorsForCharacteristic().readValueForDescriptors().begin();

        }
    }
}];
```

然而 ,只有第一次列表选择设备的时候,连接和接收数据才是正常的, 断开蓝牙再次连接的时候 出现:1.连接上其他设备 2.无法收到notify的数据了
请问我哪里使用错误了么.

---

一样的做法  我用原生蓝牙, 是完全没有问题的 

我仅仅想实现第一次连接上蓝牙之后 , 记住这次连接的蓝牙设备  ,断开蓝牙连接,再次连接上蓝牙的时候能够自动连接 不用去选择蓝牙设备    然而使用BabyBlueTooth发现问题好大  百忙之中请您看下这个问题吧..

**Comment by panzhijian** [comment]
我也碰到类似的问题  不知道您解决没  ,如果决绝了 希望你百忙之中请帮忙解决下.

**Comment by coolnameismy** [comment]
baby有个reconnet的方法可以设置自动重连，不需要每次在重新启动扫描，再委托中再次连接，这样有可能会导致未知的错误。
