### ISSUE TITLE
PeripheralViewController多次站在电子秤上   只有第一次拿到数据  后面什么方法都不走了

### ISSUE THREAD

**Issue by panzhijian** [coolnameismy/BabyBluetooth#85]
在PeripheralViewController 页面  页面有数据拿到了特征     但是我第二次站上电子秤就什么方法都不走了拿不到数据  请问我应该怎么做让我一站在电子秤上就可以拿到数据?????  希望帮忙解决下.期待你的回复.

**Comment by coolnameismy** [comment]
这个问题可能性太多了，比如设备断开链接了，channel切换了，委托重新设置了等等。 你要跟踪代码耐心排查
