### ISSUE TITLE
多平台传输

### ISSUE THREAD

**Issue by jsonseng** [coolnameismy/BabyBluetooth#86]
我想请问BabyBluetooth支持，多个平台之间的传输？iOS是Central。Android，PC作为Peripheral

**Comment by coolnameismy** [comment]
android不支持模拟peripheral。ios和mac通过编程或者软件可以支持。windows不了解。


发自我的 iPhone

在 2017年1月19日，上午9:54，jsonseng <notifications@github.com<mailto:notifications@github.com>> 写道：


我想请问BabyBluetooth支持，多个平台之间的传输？iOS是Central。Android，PC作为Peripheral

―

**Comment by jsonseng** [comment]
那我有个问题，如果是iOS通过蓝牙传输给Mac文件。是要Mac自己编写一套服务？还是本身Mac就有对应的服务，直接连接传输。

如果需要自己编写服务，以往Android之间可以通过蓝牙传输，是因为Android本身常驻一个蓝牙接受文件的服务？

**Comment by wokenshin** [comment]
Hi 大神 你的项目里面的IOSdemo 没有在info.plist中添加 蓝牙权限 IOS10运行崩溃了
Privacy - Bluetooth Peripheral Usage Description

**Comment by coolnameismy** [comment]
@wokenshin  已经处理了。

**Comment by coolnameismy** [comment]
@jsonseng  mac需要coding，使用外设模式，把自己当做外设接收数据
