### ISSUE TITLE
数据发送

### ISSUE THREAD

**Issue by yuxingmin** [coolnameismy/BabyBluetooth#88]
我对蓝牙刚开始接触，我们公司想用手机于设备蓝牙通信，手机可以给设备发送数据，也可以接收数据，我用你的BabyBluetoothAppDemo分别安装在两台真机上演示，发现两个手机都能相互连接对方，然后我点击你的按钮“写（0x11）”写数据给对方，我在A机写后，在B机上为什么无法读到数据啊 ，B机完全没反应。请大神指点。

**Comment by coolnameismy** [comment]
外设的那个demo启动的characteristics要有写入的权限，在代码里面设断点获取central写入的数据即可

**Comment by reasonpun** [comment]
大神，能否给一段demo呢，谢谢
