### ISSUE TITLE
在swift中搜索不到设备？？

### ISSUE THREAD

**Issue by miws** [coolnameismy/BabyBluetooth#9]
baby = BabyBluetooth.shareBabyBluetooth()
        babyDelegate()
        baby?.scanForPeripherals()
        baby?.begin()

并且不能象例子中的 baby?.scanForPeripherals().begin()这样使用。
以上代码在控制台只显示了：
>>>CBCentralManagerStatePoweredOn
就没有了

**Comment by coolnameismy** [comment]
sorry，babybluetooth暂不支持swift版本。后续会开发swift版本。预计3个月左右。

发自我的 iPhone

**Comment by miws** [comment]
我使用混合编程方法已经集成进入工程了，可以调用，只是没有效果。

**Comment by coolnameismy** [comment]
嗯。因为objc的链式方程是用block实现的。swift无法用。你执行单个方法可能会进委托，多个一起执行就不行了。

发自我的 iPhone

**Comment by lyluoyuan** [comment]
请教个问题，我现在做蓝牙，用bluetooth这个框架，只能搜到和连上苹果设备(mac , iphone)，即使用您这个demo也是这样的，其他有蓝牙4.0的设备搜不到或者连不上

**Comment by coolnameismy** [comment]
嗯。因为objc的链式方程是用block实现的。swift无法用。你执行单个方法可能会进委托，多个一起执行就不行了

**Comment by gnastnosaj** [comment]
babyBluetooth?.scanForPeripherals()().begin()()
这样写没用吗

**Comment by gnastnosaj** [comment]
>>>CBCentralManagerStatePoweredOn
discover perpheral Optional("L28T_00199")
discover perpheral Optional("L28T_00199")
discover perpheral Optional("L28T_00199")
discover perpheral Optional("L28T_00199")
discover perpheral Optional("AirIII")
discover perpheral Optional("L28T_00199")
discover perpheral Optional("L28T_00199")
discover perpheral Optional("AirIII")
discover perpheral Optional("AirIII")
