### ISSUE TITLE
如何同时连接两个蓝牙设备

### ISSUE THREAD

**Issue by MQTwist** [coolnameismy/BabyBluetooth#91]
现在在做一个app，要求同时连接2个设备，同时进行数据交互。应该怎么实现？是用[[BabtBluetooth alloc] init]创建2个对象？还是用单例模式创建，然后改变channel？PS：不是很清楚channel的具体作用

**Comment by coolnameismy** [comment]
可以创建2个对象，但是如果用扫描，可能同一个设备被一个扫描到后，另一个就不会扫描到了。但是一般也不会两个对象同事开扫描的。

**Comment by ZL335** [comment]
第二个创建出来的baby对象无法进行搜索操作，这是什么问题

**Comment by coolnameismy** [comment]
2个不能同时搜索，会产生冲突。 可以用一个baby的实例就可以实现。在peripheral中拆分
